#Sample CircleCI
version: 2
jobs:
    build:
      docker:
        -image: circleci/node:dubnium
      working_directory: ~/code
      steps:
        - checkout
        - run: npm install
        - run: npm test